Fix silly bug.
turnkeylinux/deck pull request #7
Opened 2023-02-23 22:48 UTC by JedMeister

Minor tweak to fix `deck -D -f /path/to/deck`.

`deck -d /path/to/deck` works fine if no processes are running in the deck. However, if processes are running, you will get an (expected) error message like this:
```
fatal: Running processes locking /path/to/deck, try again with -f|--force to kill
```

However, if `-f|--force` is used, the processes will be killed, but you will then get an error like this:
```
fatal: Cannot unmount /path/to/deck
```

It's because umount is called without the path! Doh!

2023-02-24 19:10 UTC, Christie018 approved these changes
Code changes to update deck umount command look good to me.

2023-02-26 22:44 UTC, OnGle requested changes
Could you double quote mountpath? While unlikely any of the official turnkey repos will contain a space, it's possible a 3rd party appliance developer's might.

2023-02-26 22:56 UTC, JedMeister commented
Good catch @OnGle. Your rationale is solid. I'll do that and be back in a sec.

2023-02-26 23:22 UTC, OnGle approved these changes
Looks like it was a bigger job than I first thought, looks good to me though.

2023-02-26 23:34 UTC, OnGle approved these changes
Even better!

2023-02-26 23:44 UTC, JedMeister commented
Yes it was a little bigger than I initially thought, but wasn't too hard. It just required a little more thought than I initially expected.. I've also just added the `-e` switch to `read` (just in case `IFS` is non standard).

2023-02-26 23:44 UTC, merged